
train_dataloader: 
  dataset: 
    transforms:
      ops:
        - {type: RandomPhotometricDistort, p: 0.5}
        - {type: RandomZoomOut, fill: 0}
        - {type: RandomIoUCrop, p: 0.8}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: RandomHorizontalFlip}
        - {type: Resize, size: [512, 512], }
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}   
        - {type: ConvertBoxes, fmt: 'cxcywh', normalize: True}
      policy:
        name: stop_epoch
        epoch: 72 # epoch in [71, ~) stop `ops`
        ops: ['RandomPhotometricDistort', 'RandomZoomOut', 'RandomIoUCrop']
  
  collate_fn:
    type: BatchImageCollateFuncion
    # scales: [480, 512, 544, 576, 608, 640, 640, 640, 672, 704, 736, 768, 800]
    scales: [384, 416, 448, 480, 512, 512, 512, 544, 576, 608, 640, 672, 704]
    # scales: [204, 208, 212, 216, 220, 224, 224, 224, 228, 232, 236, 240, 244]
    stop_epoch: 72 # epoch in [71, ~) stop `multiscales`

  shuffle: True
  total_batch_size: 12 # total batch size equals to 16 (4 * 4)
  num_workers: 12

val_dataloader:
  dataset: 
    transforms:
      ops: 
        - {type: Resize, size: [512, 512]}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}   
  shuffle: True
  total_batch_size: 8
  num_workers: 8